### ISSUE TITLE
The lines style should not present Fill

### ISSUE THREAD

**Issue by moovida** [Polymap4/polymap4-core#100]
Currently the style for lines in the style panel has also a Fill section. In fact that section is the one containing the color, while the stroke section is empty.

**Comment by fb71** [comment]
The Fill section is there by intention. Our style model is not equal to SLD. Our lines do have stroke *and* fill. The idea was that for a normal user it is hard to see why point and polygon have stroke and fill, but a line has not.

**Comment by moovida** [comment]
Ahh, now I see and tested it also. It makes sense. I can see the border :-) 

Mind that the cap/join stile on steep angles (ex a U-turn) is followed by the border color but not by the fill.

Closing this.
