### ISSUE TITLE
Annoing log :-)

### ISSUE THREAD

**Issue by moovida** [Polymap4/polymap4-core#101]
Would it be possible to bring this log into debug mode or even higher level. It is very verbose and fills the console:
[INFO]  WmsRenderProcessor     : Requested BBOX: 4202384.409001134,684109.0898373947,4212157.395998811,693882.0768350717
[INFO]  WmsRenderProcessor     :     WMS URL:http://ows.terrestris.de/osm/service/?SERVICE=WMS&LAYERS=OSM-WMS&CRS=EPSG:3857&FORMAT=image%2Fpng&HEIGHT=256&TRANSPARENT=TRUE&REQUEST=GetMap&WIDTH=256&BBOX=4202384.409001134,684109.0898373947,4212157.395998811,693882.0768350717&STYLES=&VERSION=1.3.0

**Comment by fb71** [comment]
Log levels are configurable now.
