### ISSUE TITLE
Update GeoServer integration 

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-core#2]
- new GeoServer version (matching GeoTools from core.data)
- neu ILayer/IMap API
- new library layout
- Java8

**Comment by fb71** [comment]
commit 8bf8cf14d56512106ef70b9e78dbce48d93c7d73
- getjars.build.xml: new repos, version: GeoServer 2.7, GeoTools 13.0
- dependencies
- Java8

**Comment by stundzig** [comment]
- only a dependency to core.project is allowed
- multi workspace mode must be checked, specialized contextClassLoader implementation should be removed if possible
- first is to start with a **Dummy**-FeatureSourceProvider to test the feature pipeline

**Comment by fb71** [comment]
Basic request are working. Issues will be handled by separate tickets.
