### ISSUE TITLE
[Style] Property activeIf...

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-core#39]
Implement support of **Style.activeIf**. The idea is to define a Boolean (constant, scale or filter dependent) that specifies the activity/visibility of the Style. It should be possibel to specify that:
- [x] a Style is active for a given particular feature attribute value
- [x] a Style is active for a given scale range

**Comment by stundzig** [comment]
Issue fixed, but could be enhanced by _concatinating the filters_
