### ISSUE TITLE
[Style] ConstantColor

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-core#43]
Specifying a constant color value.
- [x] like ConstantNumber
- [x] SLD serializer: ConstantColorHandler
- [x] UI: ConstantColorEditor (palette chooser and/or dialog?)
- [x] UIService: use service instead of context.openPanel

**Comment by stundzig** [comment]
![bildschirmfoto 2016-04-23 um 08 29 46](https://cloud.githubusercontent.com/assets/1140546/14759994/d246c0cc-0936-11e6-9e51-a3adc61fc1d6.png)
![bildschirmfoto 2016-04-23 um 08 29 33](https://cloud.githubusercontent.com/assets/1140546/14759995/d3dd5e1e-0936-11e6-8936-c3636040a052.png)

**Comment by stundzig** [comment]
-> https://github.com/Polymap4/polymap4-p4/pull/88

**Comment by fb71** [comment]
There is a new service: org.polymap.core.style.ui.UIService. It provided basic UI abstractions. Should help to decouple framework and application code.

The UIService API is simple and not yet ready. We will evolve API as we go through implementing new UI building-blocks for the styler.

**Comment by stundzig** [comment]
fixed with PR https://github.com/Polymap4/polymap4-core/pull/48
