### ISSUE TITLE
[Style] TextStyle

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-core#47]
Make a TextStyle
- [x] support all suited SLD properties
- [x] fonts should be a list of common font faces that are propable supported on most platforms

**Comment by stundzig** [comment]
Do you have an idea on how to select the attribute of the feature, which contains the text?

**Comment by stundzig** [comment]
attribute is selected vi FeatureSource from StylePropertyFieldSite

**Comment by stundzig** [comment]
works so far, additional issues are coming with separate tickets
