### ISSUE TITLE
[Style] add more font families in FontFamily.java

### ISSUE THREAD

**Issue by stundzig** [Polymap4/polymap4-core#54]
Currently i've added only 5 families, but we should add more. The correct font family names could be loaded with:

for (String family  :  
        java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames()) {
    System.out.println( family);
}

**Comment by fb71** [comment]
Nochmal grundsätzlich: mach bitte keine "es sollte" tickets.

Und zum den font-families: getLocalGraphicsEnvironment().getAvailableFontFamilyNames() wäre, wie schon gesagt, nicht besonders schlau, weil es eben nur **lokal** verfügbare fonts sind.

Zusammenfassend: 5 font-faces sind erstmal absolut ausreichend.
