### ISSUE TITLE
[GeoServer] multi-layer GetMap request

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-core#63]

**Comment by stundzig** [comment]
Ich wollte den multi-layer Request implementieren, damit ich sehr einfach ein Image vom aktuellen Kartenausschnitt mit allen aktiven Layern für das share Panel erzeugen kann. Ich hab den auskommentierten UIJob-Code angepasst. Beim 1. Request klappt alles super, beim 2. Request bleiben die Threads hängen. 

Die ganze Implementierung ist in org.polymap.service.geoserver.spring.PipelineMapResponse.formatImageOutputStream(RenderedImage, OutputStream, WMSMapContent)

Beim debuggen habe ich allerdings festgestellt, dass das Image das hier vom GetMAP Request übergeben wird, ja schon das korrekte Bild für featurebasierte Layer enthält, also auch für mehrere Layer klappt das wunderbar. Wenn ich allerdings auch ein WMS als Quelle anzapfen will, kommt nur eine Kachel mit DefaultStyle.

Wenn ich nur FeatureLayer laden möchte klappt es super, features werden geladen und unser Style wird angewendet. Das geht automatisch, ohne das in PipelineMapResponse irgendwas gemacht werden muss.

Vllt. wäre es klüger, den Geoserver auch dazu zu bringen, WMS als Quelle zu verstehen. PipelineMapResponse macht dann ja nur noch das Umwandeln in PNG oder JPEG, bzw. könnte wahrscheinlich komplett entfallen.

Was meinst Du? 

Oder übersehe ich was grundlegendes?

**Comment by fb71** [comment]
On 09.08.2016 16:38, Steffen Stundzig wrote:

> Ich wollte den multi-layer Request implementieren, damit ich sehr einfach ein
> Image vom aktuellen Kartenausschnitt mit allen aktiven Layern für das share
> Panel erzeugen kann. Ich hab den auskommentierten UIJob-Code angepasst. Beim 1.
> Request klappt alles super, beim 2. Request bleiben die Threads hängen.
> 
> Die ganze Implementierung ist in
> org.polymap.service.geoserver.spring.PipelineMapResponse.formatImageOutputStream(RenderedImage,
> OutputStream, WMSMapContent)
> 
> Beim debuggen habe ich allerdings festgestellt, dass das Image das hier vom
> GetMAP Request übergeben wird, ja schon das korrekte Bild für featurebasierte
> Layer enthält, also auch für mehrere Layer klappt das wunderbar. Wenn ich
> allerdings auch ein WMS als Quelle anzapfen will, kommt nur eine Kachel mit
> DefaultStyle.

Das verstehe ich nicht. Was bedeutet: "das Image das hier vom GetMAP Request 
übergeben wird". Welcher GetMap-Request?

> Wenn ich nur FeatureLayer laden möchte klappt es super, features werden geladen
> und unser Style wird angewendet. Das geht automatisch, ohne das in
> PipelineMapResponse irgendwas gemacht werden muss.

??? automatisch?

> Vllt. wäre es klüger, den Geoserver auch dazu zu bringen, WMS als Quelle zu
> verstehen. PipelineMapResponse macht dann ja nur noch das Umwandeln in PNG oder
> JPEG, bzw. könnte wahrscheinlich komplett entfallen.

???

PipelineMapResponse leitet den Request durch die Pipeline. Diese macht rendern, 
encode, decode und vielleicht projekt-spezifische dinge, feature-type anpassen, 
einfach alles. Wie könnte das entfallen?

> Was meinst Du?

Ich meine, dass ich nicht genau verstehe was du machen willst.

> Oder übersehe ich was grundlegendes?

weiß ich nicht genau gerade. PipelineMapResponse ist der zentrale übergabepunkt 
an dem der kontroll- und und daten-fluss vom GeoServer in unsere Pipeline 
eingeleitet wird. Die OGC/WMS/WFS_requests werden in Pipeline-Request umgesetzt

**Comment by stundzig** [comment]
Das ganze Erzeugen der Bilder wird in `org.geoserver.wms.GetMap.executeInternal(WMSMapContent, GetMapRequest, GetMapOutputFormat, List<Object>, List<Object>)` angestossen. Da wir bei allen Layern einfach nur type=0 dranschreiben, kommen wir in dem if Block immer in `} else if (layerType == MapLayerInfo.TYPE_VECTOR) {`. Wenn wir das auch ändern möchten, müssten wir die Klasse GetMap ersetzen.

Weiterhin wird dann für den geforderten mimetype ein entsprechender Producer geladen. Producer sind Instanzen von **GetMapOutputFormat**, bspw. für alle Arten von Bildern eben **org.geoserver.wms.map.RenderedImageMapOutputFormat**.

Im Spring ist das auch zu erkennen, bspw. der Block:

```
<bean id="JPEGMapProducer" class="org.geoserver.wms.map.RenderedImageMapOutputFormat">
      <constructor-arg>
        <description>The prescribed output format MIME-Type, same as declared in the getcaps document</description>
        <value>image/jpeg</value>
      </constructor-arg>
      <constructor-arg ref="wms" />
      <property name="transparencySupported">
        <description>JPEG does not support transparency</description>
        <value>false</value>
      </property>
      <property name="paletteSupported">
        <description>JPEG does not support 8-bit indexed color maps</description>
        <value>false</value>
      </property>
      <property name="extension" value="jpg"/>
    </bean>
    <!--bean id="JPEGMapResponse" class="org.geoserver.wms.map.JPEGMapResponse">
      <constructor-arg ref="wms" />
    </bean-->
```

enthält den Producer und der die Response-Klasse. Verbunden sind die beiden über den MimeType. Also ein Producer gibt an, dass er **image/jpeg** kann und ein Response registriert sich ebenfalls für einen Mimetype und ist dann dafür zuständig, den erzeugten Value aus dem Producer zu encoden.

Beim PDFMapOutputFormat(Producer) und PdfMapResponse(Encoder) ist das gut zu erkennen. Die haben so ein ähnliches Muster wie wir auch aktuell haben könnten. Der Producer produziert in dem Falle gar nichts, sondern merkt sich nur alle Daten und der Response macht dann das eigentliche Erstellen des PDF und startet auch wieder händisch den StreamingRenderer. Heisst korrekterweise müssten wir den auch anpassen und unsere Pipeline da einbauen.

Mein Vorschlag, wir ersetzen **RenderedImageMapOutputFormat** durch unsere Pipeline-Producer Implementierung und lassen entweder ein RenderedImage erzeugen, dass dann von den vorhandenen Responses nur noch encodiert wird. Oder wir lassen unseren Producer auch gleich das encoding machen und konfigurieren einen Response der einfach nichts tut. 

Wenn unser Producer auch das encoding macht, sollte der dann auch gleich ein PDF erzeugen können, so wie im **PdfMapResponse**.

Wenn unser Producer die RenderedImages erzeugt, dann müssen wir einen neuen **PdfMapResponse** bauen, der dieses Image dann in das PDF reinbaut.

**Comment by stundzig** [comment]
Ich kann das auch implementieren, du müsstest mir nur sagen, welche Variante bevorzugt wäre. Ich würde unseren Producer das **RenderedImage** bauen lassen und das Schreiben in den OutputStream dann den **Response**-Klassen überlassen.

**Comment by stundzig** [comment]
Ich hab jetzt die Klasse **PipelineMapOutputFormat** fertig, die das Erzeugen der Bilder macht. Es wird jeweils ein RenderedImage erzeugt, dass dann entsprechend von den MapReponses wie jpeg, png usw. encodiert wird. Das klappt super. Das kann ich jetzt auch für den Input in den PDFResponse nutzen.

Auch beim multi layer klappt das genau beim 1. Request. Beim zweiten Request bleibt er im StreamingRenderer hängen. Dort wird ein FeatureIterator benutzt und beim hasNext() wird blockiert. Der FeatureIterator selbst delegiert an **org.polymap.core.data.AsyncPipelineFeatureCollection.AsyncPipelineIterator.hasNext()** und in der Zeile 221 **queue.take()** geht es nicht weiter.

Kann es sein, dass das am fehlenden SessionContext liegt oderso? Komisch ist nur, dass es beim 1. mal geht.

**Comment by stundzig** [comment]
Tatsächlich. Ich hab im GeoserverServlet jetzt einen SessionContext aufgemacht, mit einer Session die über die gesamt Servlet-Lebenszeit erhalten bleibt und es geht. Super.

**Comment by fb71** [comment]
So, ich hoffe ich habe alles beachtet. GeoServerServlet hat wieder einen SessionContext. init(), service() und destroy() werden innerhalb dieses Contextes ausgeführt. Das müsste alle GeoServer-Innereien abdecken. #map kommt ebenfalls aus diesem Context.

Auf Events hören und den GeoServer ggf. neustarten macht jetzt Arenas GeoServerStarter (zusammen mit dem OnDemandServlet). Das ist viel schöner als früher :)

**Comment by stundzig** [comment]
fixed in https://github.com/Polymap4/polymap4-core/pull/79
