### ISSUE TITLE
[Style] Scale dependent number

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-core#82]
Seems that steps are notequaly distributed over the given scale range.

Instead of for example: 1 - 2 - 3 - 4 - 5
it is more like:        1 - 1 - 1 - 5 - 5

**Comment by stundzig** [comment]
fixed in https://github.com/Polymap4/polymap4-core/commit/e47eecc44266c7e1a406d8b1e1729366d64a5043
